AuScope/portal-core

src/main/webapp/portal-core/js/portal/charts/3DScatterPlot.js
Fixed 3DScatterPlot capturing scroll events for the entire page. Now limited to capturing scroll events inside the 3DScatterPlot container.
=> EAVL-39 Fixed 3DScatterPlot capturing scroll events

src/main/webapp/portal-core/js/admin/TestResultsPanel.js, src/main/webapp/portal-core/js/portal/csw/themefilter/CSWFilterResultsPanel.js, src/main/webapp/portal-core/js/portal/layer/downloader/wfs/KLWFSDownloader.js, src/main/webapp/portal-core/js/portal/layer/downloader/wfs/WFSDownloader.js, src/main/webapp/portal-core/js/portal/layer/renderer/wfs/FeatureWithMapRenderer.js, src/main/webapp/portal-core/js/portal/layer/renderer/wms/LayerRenderer.js, src/main/webapp/portal-core/js/portal/widgets/panel/BaseRecordPanel.js, src/main/webapp/portal-core/js/portal/widgets/panel/CSWRecordPagingPanel.js, src/main/webapp/portal-core/js/portal/widgets/panel/CSWReportPagingPanel.js, src/main/webapp/portal-core/js/portal/widgets/panel/LayerPanel.js
Image references now point to the portal core artifact.
=> Image ref cleanup

eclipse-format-java-modest.xml
This is a minimal formatter profile (no tabs, 120-character lines).
=> Add a modest Java formatter profile for eclipse.

src/main/webapp/portal-core/js/portal/widgets/field/WMSCustomSearchField.js
Remove the prvious active layer from the map before the custom wms url search.
=> Bug fix for AUS-2592.4.

src/main/webapp/portal-core/js/portal/widgets/grid/plugin/RowExpanderContainer.js, src/main/webapp/portal-core/js/portal/widgets/panel/BaseRecordPanel.js
See https://jira.csiro.au/browse/AUS-2588
=> AUS-2588 Fixing JS error on layer open

src/main/webapp/portal-core/js/portal/widgets/grid/plugin/RowExpanderContainer.js
Reverted unnecessary changes to RowExpanderContainer
=> AUS-2588 Amended commit

src/main/java/org/auscope/portal/core/services/BaseWFSService.java, src/main/java/org/auscope/portal/core/services/responses/wfs/WFSGetCapabilitiesResponse.java, src/main/java/org/auscope/portal/core/services/responses/wms/GetCapabilitiesWMSLayerRecord.java, src/main/java/org/auscope/portal/core/services/responses/wms/GetCapabilitiesWMSLayer_1_1_1.java, src/main/java/org/auscope/portal/core/services/responses/wms/GetCapabilitiesWMSLayer_1_3_0.java, src/main/resources/org/auscope/portal/core/test/responses/wfs/GetCapabilitiesResponse.xml, src/main/resources/org/auscope/portal/core/test/responses/wms/GetCapabilitiesControllerWMSResponse_1_1_1.xml, src/main/webapp/portal-core/js/portal/csw/OnlineResource.js, src/main/webapp/portal-core/js/portal/layer/legend/wms/WMSLegend.js, src/main/webapp/portal-core/js/portal/layer/legend/wms/WMSLegendForm.js, src/main/webapp/portal-core/js/portal/widgets/panel/BaseRecordPanel.js, src/main/webapp/portal-core/js/portal/widgets/panel/LayerPanel.js, src/main/webapp/portal-core/js/portal/widgets/panel/OnlineResourcesPanel.js, src/main/webapp/portal-core/js/portal/widgets/window/CSWRecordDescriptionWindow.js, src/test/java/org/auscope/portal/core/services/TestWMSService.java
Changes to the Service Information dialog to support Geoscience Australia's version of the dialog. It is the portal's responsibility to override the dialog if desired. If no override is specified then the dialog will be the old Auscope Portal version of the dialog. 
Our plan is to show the CSIRO guys our dialog in action, and if they like what they see we'll add a pull request with the portal-side changes.
=> Service info

src/main/webapp/portal-core/js/portal/map/openlayers/OpenLayersMap.js
- Add new base layer to the OpenLayers panel. Displays as mostly-white with light country outlines.
- The ActiveLayers panel for these base layers has been resized for this in (geoscience-) portal's
mainUI.js - see https://github.com/GeoscienceAustralia/geoscience-portal/commit/f7cfa7a57c08c7adf5ee0ff62854da2853bc71b3.
=> GPT-101 - World Political Boundaries

src/main/java/org/auscope/portal/core/services/responses/csw/CSWRecord.java, src/main/java/org/auscope/portal/core/services/responses/csw/CSWRecordTransformer.java, src/main/java/org/auscope/portal/core/view/ViewCSWRecordFactory.java, src/main/resources/org/auscope/portal/core/test/responses/csw/cswRecordResponse_MultipleDatasetURIs.xml, src/main/resources/org/auscope/portal/core/test/responses/csw/cswRecordResponse_SingleDatasetURI.xml, src/main/webapp/portal-core/js/portal/csw/CSWRecord.js, src/test/java/org/auscope/portal/core/services/responses/csw/TestCSWRecordTransformer.java, src/test/java/org/auscope/portal/core/view/TestViewCSWRecordFactory.java
Portal core changes to support the datasetURI element in a CSWRecord. Actually it's an array as according to the schema it can be zero or many elements
=> GPT-105 Download data

src/main/java/org/auscope/portal/core/services/responses/wms/GetCapabilitiesRecord_1_1_1.java
Heya did this work before going on XMas holidays.
Added check for null MetadataURL in unit test
probably should actually add the element to the test xml as well.
=> GPT - NOISSUE - unit tests

src/main/java/org/auscope/portal/core/services/responses/wms/GetCapabilitiesRecord_1_1_1.java
Reverts AuScope/portal-core#90
=> Revert "GPT - NOISSUE - unit tests"

src/main/webapp/portal-core/js/portal/widgets/panel/CommonBaseRecordPanel.js
The Netcdf Subset Service will now (for the purposes of GUI notifications) be recorded as a data service.
=> ANVGL-39 Added NCSS as a data service

src/main/java/org/auscope/portal/core/server/http/HttpServiceCaller.java
As part of diagnosing issues with some POST requests I noticed that the HttpServiceCaller couldn't really log anything to do with a POST body.
I've updated the method invocation to include printing out the first 100KB of a POST body. This code block is ONLY active if log4j TRACE is set. 
This brings the POST behaviour in line with the GET TRACE logging.
=> Improved TRACE logging for POST requests

src/main/java/org/auscope/portal/core/services/responses/wms/GetCapabilitiesRecord.java, src/main/java/org/auscope/portal/core/services/responses/wms/GetCapabilitiesRecord_1_1_1.java, src/main/java/org/auscope/portal/core/services/responses/wms/GetCapabilitiesRecord_1_3_0.java
The extra commit in here should fix the null pointer that broke the unit tests.
=> Gpt 122 metadata url

src/main/webapp/portal-core/js/portal/layer/renderer/wms/DisjunctionLayerRenderer.js
The layer name and service URL were mixed up on the filterer side of things. This was breaking the query tool
=> GPT-133 render disjuncted layers

src/main/java/org/auscope/portal/core/server/controllers/BaseCSWController.java, src/main/java/org/auscope/portal/core/services/KnownLayerService.java, src/main/java/org/auscope/portal/core/services/responses/csw/CSWRecord.java, src/main/java/org/auscope/portal/core/services/responses/csw/CSWRecordTransformer.java, src/main/java/org/auscope/portal/core/view/knownlayer/WMSSelectors.java, src/test/java/org/auscope/portal/core/services/KnownLayerServiceTest.java
This change is about making conjuncted layers (AND'ed) display in the order specified in the known layers config rather than the order that comes from the server.
=> GPT-103 reapplying Brooke Smith changes with NPE fix as well

src/main/webapp/portal-core/js/portal/layer/querier/wms/WMSMultipleTabDisplayQuerier.js
added callback invocation which removes the load mask
=> GPT-179 map freeze after query

src/main/webapp/portal-core/js/portal/layer/legend/wms/WMSLegendForm.js
Skip over url if the image cannot be loaded as we only need one successful legend image from all of the online resources in the layer
=> GPT-145--SLD-legend

src/main/webapp/portal-core/js/portal/layer/legend/wms/WMSLegend.js, src/main/webapp/portal-core/js/portal/widgets/panel/FilterPanel.js
Fixed issue of too small for legend icon size.
=> AUS-2619 Fixed issue of opening multiple legend for a layer.

src/main/java/org/auscope/portal/core/view/ViewKnownLayerFactory.java, src/main/java/org/auscope/portal/core/view/knownlayer/KnownLayer.java, src/main/webapp/portal-core/js/portal/knownlayer/KnownLayer.js, src/main/webapp/portal-core/js/portal/layer/Layer.js, src/main/webapp/portal-core/js/portal/layer/legend/Legend.js, src/main/webapp/portal-core/js/portal/layer/legend/wfs/WFSLegend.js, src/main/webapp/portal-core/js/portal/layer/legend/wms/WMSLegend.js, src/main/webapp/portal-core/js/portal/layer/legend/wms/WMSLegendForm.js, src/main/webapp/portal-core/js/portal/layer/renderer/wms/LayerRenderer.js
added support for static legend graphics
added configuration from portal to use getCapabilities before trying getLegendGraphics. Perhaps this should be the default, but with this change the portal can decide which method to try first
=> GPT-145 legend popup

src/main/webapp/portal-core/js/portal/layer/legend/wms/WMSLegend.js, src/main/webapp/portal-core/js/portal/layer/querier/Querier.js, src/main/webapp/portal-core/js/portal/layer/querier/wfs/WFSWithMapQuerier.js, src/main/webapp/portal-core/js/portal/layer/renderer/wms/LayerRenderer.js, src/main/webapp/portal-core/js/portal/map/openlayers/primitives/WMSOverlay.js
Adds support for ArcGIS layers in the form of permitting SLDs to GetMap and GetLegendGraphic requests, while preventing them from being sent to GetFeatureInfo requests for the same services.
=> GPT-211 Applying SLD to ArcGIS Server WMS layers

src/main/webapp/portal-core/js/portal/layer/renderer/wms/LayerRenderer.js
If a proxyStyleUrl exists makes call to the URL to get the style, otherwise defaults to rendering with no style
=> GPT-211 Removes getDefaultStyle fallback

src/main/webapp/portal-core/js/portal/layer/renderer/wfs/FeatureWithMapRenderer.js
=> Gpt 206  tenements layer not render at first attempt

src/main/webapp/portal-core/js/portal/widgets/panel/CommonBaseRecordPanel.js
Change service unavailable icon from red cross to yellow warning.
=> GPT-214 Change icon

src/main/java/org/auscope/portal/core/cloud/CloudFileInformation.java, src/main/java/org/auscope/portal/core/services/cloud/CloudStorageService.java, src/test/java/org/auscope/portal/core/services/cloud/TestCloudStorageService.java
Added a new getJobFileMetadata method to the cloud storage service
Added an optional "hash" field to CloudFileInformation
All backwards compatible.
=> ANVGL-130 Added file metadata query

src/main/webapp/portal-core/js/portal/widgets/panel/FilterPanel.js
If the number of menu items for the options button is one, make that item
a button itself.
=> GPT-246 Remove or replace Options button

src/main/webapp/portal-core/js/portal/widgets/panel/RecordPanel.js
Added a little utility function that allows individual records to be expanded programmatically.
=> AUS-2622 Added an "expandRecordById" function

src/main/webapp/portal-core/js/portal/layer/querier/QueryTargetHandler.js
Added title and styling information
=> AUS-2638 Choice dialog has transparent window bar

src/main/webapp/portal-core/js/portal/layer/LayerStore.js, src/main/webapp/portal-core/js/portal/map/BaseMap.js, src/main/webapp/portal-core/js/portal/map/openlayers/ActiveLayerManager.js
Cannot repeatedly add layers to NVCL report without clicking on remove layer icon
=> AUS-2714 Cannot repeatedly add layers to NVCL report without clicking on

src/main/webapp/portal-core/js/portal/widgets/panel/recordpanel/GroupPanel.js, src/main/webapp/portal-core/js/portal/widgets/panel/recordpanel/RecordPanel.js
RecordPanel will now respond (as you'd expect) to items being added/removed from the underlying store. Support for both grouped/ungrouped modes.
=> AUS-2732 Support for store add/remove events

src/main/webapp/portal-core/css/auscope-portal-core.css, src/main/webapp/portal-core/js/portal/widgets/panel/recordpanel/AbstractChild.js, src/main/webapp/portal-core/js/portal/widgets/panel/recordpanel/RecordPanel.js, src/main/webapp/portal-core/js/portal/widgets/panel/recordpanel/RowPanel.js
Added a "allowReordering" flag to RecordPanel. This will only work with a store in non grouped mode. It will allow the user to drag/drop reorder any row and the changes will be reflected in the underlying store ordering.
=> AUS-2754 Support for RecordPanel Drag/Drop reordering

src/main/java/org/auscope/portal/core/services/methodmakers/filter/csw/CSWGetDataRecordsFilter.java
Added a new search option to the CSW filter that supports the CSW 2.0.2 compliant modified keyword
=> ANVGL-13 Added the CSW compliant "Modified" attribute

src/main/webapp/portal-core/js/portal/widgets/panel/BaseRecordPanel.js
Made BaseRecordPanel search bar hideable so that children have a choice as to whether to use it or not.
=> ANVGL-13 Made BaseRecordPanel search bar hideable

src/main/webapp/portal-core/js/portal/widgets/panel/CSWMetadataPanel.js
This fixes a regression with an earlier modification to this file.
=> ANVGL-13 Fixed CSWMetadataPanel child items not correctly concatenating

src/main/java/org/auscope/portal/core/services/CSWCacheService.java, src/main/resources/org/auscope/portal/core/test/responses/csw/cswRecordResponse_SingleRecordNoMore.xml, src/test/java/org/auscope/portal/core/services/TestCSWCacheService.java
The keyword caching has been extended to include the ability to request keywords by individual endpoints.
=> ANVGL-13 Support for requesting keywords by endpoint

src/main/java/org/auscope/portal/core/services/cloud/CloudComputeService.java, src/main/java/org/auscope/portal/core/services/cloud/CloudStorageService.java, src/main/java/org/auscope/portal/core/services/cloud/CloudStorageServiceJClouds.java, src/test/java/org/auscope/portal/core/services/cloud/MockCloudStorageService.java, src/test/java/org/auscope/portal/core/services/cloud/TestCloudStorageService.java
Some re-factoring to allow support for NCI Raijin HPC
=> Vgl 175 - Support for NCI Raijin

src/main/java/org/auscope/portal/core/server/controllers/BasePortalController.java
Fixed up a case where an InputStream would be serialised by Jackson/JSON.
=> Fixed WFS serialising input stream

src/main/webapp/portal-core/js/portal/map/openlayers/OpenLayersMap.js
Replaced a known failed GA ESRI Webserver with its replacement service.
=> Updated baselayer reference to working service

src/main/java/org/auscope/portal/core/services/cloud/CloudComputeService.java, src/main/java/org/auscope/portal/core/services/cloud/CloudComputeServiceAws.java, src/main/java/org/auscope/portal/core/services/cloud/CloudComputeServiceNectar.java
Compute types are now filtered to match image requirements:
https://jira.csiro.au/browse/VGL-196
=> Fixes VGL-196

src/main/webapp/portal-core/js/portal/layer/querier/Querier.js, src/main/webapp/portal-core/js/portal/layer/querier/wfs/WFSWithMapQuerier.js
Some layers provided by SA were failing because they could not handle a GET request with an SLD. Changed the logic and refactored such that SLD body length was consistent across query classes and the right method was used depending on WMS implementation (POST or GET).
=> Fix failing WMS GetFeatureInfo for SA layers

src/main/webapp/portal-core/js/portal/util/Ajax.js
Added (optional) access to the underlying response object so that callbacks can test HTTP response codes and other low level details if required.
=> VGL-213 Added optional Ajax response obj to callback

src/main/webapp/portal-core/js/portal/widgets/panel/CSWMetadataPanel.js
GA intend  to release the data in future in an open fashion without passwords
usage conditions and 'I accept' buttons.
=> AUS-2790 Removed obsolete warning message

src/main/webapp/portal-core/js/portal/layer/legend/csw/CSWLegend.js, src/main/webapp/portal-core/js/portal/layer/renderer/csw/CSWRenderer.js, src/main/webapp/portal-core/jsimports.jsp
This adds a legend to all the CSW reports - see attached picture.
=> AUS-2807 Added a legend for CSW reports

src/main/java/org/auscope/portal/core/services/SISSVoc3Service.java, src/main/java/org/auscope/portal/core/services/methodmakers/sissvoc/SISSVoc3MethodMaker.java, src/main/java/org/auscope/portal/core/services/namespaces/VocabNamespaceContext.java, src/main/webapp/portal-core/js/portal/layer/querier/wfs/factories/BaseFactory.js, src/test/java/org/auscope/portal/core/services/TestSISSVoc3Service.java, src/test/java/org/auscope/portal/core/services/methodmakers/sissvoc/TestSISSVoc3MethodMaker.java
Plus a few changes additions to namespaces to assist
=> GPT-464 - Change to SISSVoc interactions to enable ERML and ERML Lite

src/main/java/org/auscope/portal/core/services/CSWCacheService.java, src/test/java/org/auscope/portal/core/services/TestCSWCacheService.java
Caches CSW records from each endpoint. On subsequent cache updates, if a CSW service fails, the cached records for that endpoint are used instead of dropping the previous values.
After starting the portal and allowing it to harvest CSW records normally, test the fallback function by forcing one or more of the CSW endpoints to fail (e.g. redirect the CSW endpoint hostname to localhost in /etc/hosts). The layers from that catalogue should still appear in the portal based on the cached values, instead of being marked as invalid like previously.
=> Fallback onto cached CSW records on CSW failure.

src/main/java/org/auscope/portal/core/services/methodmakers/filter/csw/CSWGetDataRecordsFilter.java
Allows us to do advanced filtering on those services that have WMS as their gmd:protocol for their online resources.
=> Filter on online resource type

src/main/java/org/auscope/portal/core/server/controllers/CSWFilterController.java
And replace spaces with single character wildcard.
GA's registry search queries for both services and datasets, and all
CSW implementations we have encountered do not like spaces in their
keywords.
Therefore I we replace spaces with the single character wildcard
=> Default to all types for CSW search

src/main/webapp/portal-core/js/portal/layer/downloader/wfs/KLWFSDownloader.js
Modified text to better explain what would be downloaded.
=> Modify text

src/main/webapp/portal-core/js/portal/layer/downloader/wfs/KLWFSDownloader.js
Removes radio buttons, instead a checkbox on by default that says "Filter my download by the map bounds". Removed "Filter by original bounds" as that was seen as unnecessary.
=> Change download logic

src/main/java/org/auscope/portal/core/services/responses/csw/CSWRecord.java, src/main/java/org/auscope/portal/core/services/responses/csw/CSWRecordTransformer.java, src/main/java/org/auscope/portal/core/view/ViewCSWRecordFactory.java, src/test/java/org/auscope/portal/core/view/TestViewCSWRecordFactory.java
made changes to pick up MT data legal constraint fields  (use limitation and access constraints)
https://jira.csiro.au/browse/DEVL-56
=> Devl 56 mt data legal

src/main/java/org/auscope/portal/core/services/responses/csw/CSWRecord.java, src/main/java/org/auscope/portal/core/services/responses/csw/CSWRecordTransformer.java, src/main/java/org/auscope/portal/core/view/ViewCSWRecordFactory.java, src/main/webapp/portal-core/js/portal/layer/querier/QueryTargetHandler.js, src/test/java/org/auscope/portal/core/view/TestViewCSWRecordFactory.java
Some layers are scale dependent, therefore we indicate this in the
associated CSW record.
=> New scale fields for CSW records

src/main/java/org/auscope/portal/core/services/CSWCacheService.java
Copy of email below
---
I found a strange portal bug that only occurs in a certain set of circumstances. It's not easy to reproduce, but I will describe it here:
1. The serialisation of CSW endpoints are saved to a temp directory, eg /temp/cswEndpoint.ser
2. A code change to the structure of CSWRecord happens such that the old serialised file can't be deserialised into a CSWRecord (eg recent changes to CSWRecord in portal-core)
3. One or more CSW endpoints is either indexing or down at the time of executing a CSWCacheUpdateThread
4. The block of code at the following link catches an exception at line 654 due to the above three criteria
5. https://github.com/AuScope/portal-core/blob/master/src/main/java/org/auscope/portal/core/services/CSWCacheService.java#L654
6. The attemptCleanup method …
=> Reorder logic, handle exception better

src/main/webapp/portal-core/js/portal/layer/downloader/wfs/KLWFSDownloader.js
Causes error with rendering panel
=> Put div back inside loop

src/main/java/org/auscope/portal/core/server/controllers/CSWFilterController.java, src/main/java/org/auscope/portal/core/services/methodmakers/filter/csw/CSWGetDataRecordsFilter.java
added capability to search csw records with fileidentifier.
=> added capability to search csw records with fileidentifier.

src/main/java/org/auscope/portal/core/view/ViewKnownLayerFactory.java, src/main/java/org/auscope/portal/core/view/knownlayer/KnownLayer.java
Allows the developer to wire in a style provided by the service
=> Add configuration for WMS STYLES parameter

src/main/java/org/auscope/portal/core/server/controllers/WFSController.java, src/main/java/org/auscope/portal/core/server/controllers/WMSController.java
These methods existed in WMSController and WFSController in the AusGIN
Portal, now moving them over to their respective controllers in
portal-core
=> Add ability to display metadata URL from GetCapabilities

pom.xml, src/main/java/org/auscope/portal/core/services/SISSVoc3Service.java, src/main/java/org/auscope/portal/core/services/VocabularyCacheService.java, src/main/java/org/auscope/portal/core/services/VocabularyFilterService.java, src/main/java/org/auscope/portal/core/services/VocabularyService.java, src/test/java/org/auscope/portal/core/services/TestSISSVoc3Service.java, src/test/java/org/auscope/portal/core/services/TestVocabularyCacheService.java, src/test/java/org/auscope/portal/core/services/TestVocabularyFilterService.java, src/test/java/org/auscope/portal/core/services/TestVocabularyService.java
Updated Xerces, AWS and jena packages to resolve security warnings
Note: jena package name changed from com.hp.hpl.jena to org.apache.jena
=> Updated some dependencies to resolve security warnings

src/main/java/org/auscope/portal/core/services/cloud/CloudStorageServiceJClouds.java
Make sure that JClouds auth endpoint is not null before doing any Keystone v3 checks.
=> Fix AWS endpoint check

pom.xml
Bump servlet API to 3.0.1 to enable annotation configuration
=> Upgrade servlet API to 3.0.1

src/main/java/org/auscope/portal/core/services/responses/csw/AbstractCSWOnlineResource.java, src/main/java/org/auscope/portal/core/services/responses/csw/CSWOnlineResourceFactory.java, src/main/java/org/auscope/portal/core/services/responses/csw/CSWOnlineResourceImpl.java, src/main/java/org/auscope/portal/core/view/ViewCSWRecordFactory.java, src/test/java/org/auscope/portal/core/view/TestViewCSWRecordFactory.java
Add a CSW record's protocolRequest field to the portal-core model.
=> Add protocol request field to CSWOnlineResourceImpl

src/main/java/org/auscope/portal/core/server/controllers/CSWSearchController.java
Add CSW server type from DCDP. Other CSW related changes have already been incorporated.
=> Add CSW server type

src/main/java/org/auscope/portal/core/server/controllers/CSWFilterController.java, src/main/java/org/auscope/portal/core/server/controllers/WMSController.java, src/main/java/org/auscope/portal/core/services/CSWService.java, src/main/java/org/auscope/portal/core/services/NamespaceService.java, src/main/java/org/auscope/portal/core/services/WMSService.java, src/main/java/org/auscope/portal/core/services/methodmakers/WMS_1_3_0_MethodMaker.java, src/main/java/org/auscope/portal/core/services/namespaces/CSWNamespaceContext.java, src/main/java/org/auscope/portal/core/services/responses/csw/CSWRecord.java, src/main/java/org/auscope/portal/core/services/responses/csw/CSWRecordTransformer.java, src/main/java/org/auscope/portal/core/services/responses/csw/CSWTemporalExtent.java, src/main/java/org/auscope/portal/core/services/responses/wms/GetCapabilitiesWMSLayerRecord.java, src/main/java/org/auscope/portal/core/services/responses/wms/GetCapabilitiesWMSLayer_1_1_1.java, src/main/java/org/auscope/portal/core/services/responses/wms/GetCapabilitiesWMSLayer_1_3_0.java, src/main/java/org/auscope/portal/core/view/ViewCSWRecordFactory.java, src/test/java/org/auscope/portal/core/view/TestViewCSWRecordFactory.java
Added a CSWTemporalExtent (beginPosition, endPosition) object for CSWRecords.
Added a timeExtent (String[]) field to WMS GetCapabilities responses.
Updated GML namespace to 3.2.
=> Add CSW and WMS time support

src/test/resources/log4j.properties
Remove anything related to yilgarn.
=> AUS-3468: delete yilgarn layers

src/main/java/org/auscope/portal/core/server/http/download/ServiceDownloadManager.java, src/main/java/org/auscope/portal/core/services/CSWCacheService.java, src/main/java/org/auscope/portal/core/uifilter/GenericFilterAdapter.java
Now caching the CSW cache on the filesystem for faster backend startup
Minor cosmetic code changes to comform to best practices
=> Now caching the CSW cache on the filesystem for faster backend startup

src/main/java/org/auscope/portal/core/server/controllers/KnownLayerController.java, src/main/java/org/auscope/portal/core/server/controllers/WCSController.java, src/main/java/org/auscope/portal/core/server/controllers/WMSController.java, src/main/java/org/auscope/portal/core/services/KnownLayerService.java, src/main/java/org/auscope/portal/core/services/responses/csw/AbstractCSWOnlineResource.java, src/main/java/org/auscope/portal/core/services/responses/wcs/SimpleEnvelope.java, src/main/java/org/auscope/portal/core/services/responses/wcs/SpatialDomain.java, src/main/java/org/auscope/portal/core/services/responses/wcs/TimeConstraint.java, src/main/java/org/auscope/portal/core/services/responses/wms/GetCapabilitiesWMSLayer_1_3_0.java, src/main/java/org/auscope/portal/core/view/ViewGetCapabilitiesFactory.java, src/main/java/org/auscope/portal/core/view/knownlayer/KnownLayerAndRecords.java, src/main/resources/org/auscope/portal/core/test/responses/wcs/DescribeCoverageResponse1.xml, src/test/java/org/auscope/portal/core/server/controllers/TestBaseCSWController.java, src/test/java/org/auscope/portal/core/server/controllers/TestGetCapabilitiesController.java, src/test/java/org/auscope/portal/core/server/controllers/TestWCSController.java, src/test/java/org/auscope/portal/core/services/KnownLayerServiceTest.java, src/test/java/org/auscope/portal/core/services/TestKnownLayerService.java, src/test/java/org/auscope/portal/core/services/responses/wcs/TestDescribeCoverageRecord.java
Changes to detect and support the usage of time parameters in WMS and WCS requests
=> Aus 3598 Changes to detect and support the usage of time parameters in WMS and WCS requests

pom.xml, src/main/java/org/auscope/portal/core/server/controllers/WMSController.java, src/main/java/org/auscope/portal/core/services/CSWCacheService.java, src/main/java/org/auscope/portal/core/services/methodmakers/WMS_1_3_0_MethodMaker.java
Switched to Java 17
Better Exception handling in GetMap proxy -> might result in better error reporting at the front end too.
Small cosmetic changes
=> Switched to Java 17 and other small changes

src/main/java/org/auscope/portal/core/cloud/CloudDirectoryInformation.java, src/main/java/org/auscope/portal/core/services/cloud/CloudStorageService.java, src/main/java/org/auscope/portal/core/services/cloud/CloudStorageServiceJClouds.java
Added a CloudDirectoryInformation class to represent a job output directory, and a method to retrieve it from cloud.
=> INSAR-46 Job Output Directories

src/main/java/org/auscope/portal/core/services/CSWCacheService.java, src/main/java/org/auscope/portal/core/util/FileIOUtil.java, src/test/java/org/auscope/portal/core/services/TestCSWCacheService.java
Added cacheDirectory configuration.
=> AUS-3667 Fixed cache file dispear issue.

src/main/java/org/auscope/portal/core/services/CSWCacheService.java
added getUpdateRunning method to check CSWCache status.  This is required for the new AuScope Portal API actuator health Indicator.
=> added getUpdateRunning method to check CSWCache status

src/main/java/org/auscope/portal/core/server/controllers/WFSController.java, src/main/java/org/auscope/portal/core/util/HttpUtil.java
Add a URL encoding method, some AusLAMP layers had spaces in the parameters.
=> AUS-3725-AusLAMP-Layers

src/main/java/org/auscope/portal/core/server/controllers/DownloadController.java
When downloading data use the filename in the URL as the zip filename if available
=> AUS-3719 When downloading data use the filename in the URL as the zip filename

src/main/java/org/auscope/portal/core/services/CSWCacheService.java, src/main/java/org/auscope/portal/core/services/csw/CSWServiceItem.java
Also renamed 'endPoint' to 'cswService' in some functions to remove ambiguity with the class level 'endPoint'.
All references to class level 'endPoint' were renamed to 'this.endPoint' for the same reason
=> AUS-3769 Ability to specify CSW service request page size

src/main/java/org/auscope/portal/core/services/responses/csw/CSWRecordTransformer.java
Changed how constraints are constructed from CSW record data.
=> AUS-3513 CSW Constraints

src/main/java/org/auscope/portal/core/services/responses/csw/CSWContactFactory.java, src/main/java/org/auscope/portal/core/services/responses/csw/CSWRecord.java, src/main/java/org/auscope/portal/core/services/responses/csw/CSWRecordTransformer.java, src/main/java/org/auscope/portal/core/view/ViewCSWRecordFactory.java, src/test/java/org/auscope/portal/core/view/TestViewCSWRecordFactory.java
Add funder field to CSWRecord.
=> AUS-3683 Funder Info

pom.xml, src/main/java/org/auscope/portal/core/server/controllers/SearchController.java, src/main/java/org/auscope/portal/core/services/KnownLayerService.java, src/main/java/org/auscope/portal/core/services/SearchService.java, src/test/java/org/auscope/portal/core/server/controllers/TestBaseCSWController.java, src/test/java/org/auscope/portal/core/services/KnownLayerServiceTest.java, src/test/java/org/auscope/portal/core/services/TestKnownLayerService.java
Added a search controller and service for indexing layers/CSW records and being able to search the index via Lucene.
=> AUS-3808 Improved Search

src/main/java/org/auscope/portal/core/services/SearchService.java
Query escaping moved to front end where it can better be determined what needs to be escaped.
=> AUS-3824 Search filtering fix

src/main/java/org/auscope/portal/core/services/SearchService.java
Fixed issue with search document comparison returning true despite one document having less fields.
=> AUS-3830 Search Document Comparison Fix

src/main/java/org/auscope/portal/core/services/CSWCacheService.java
Ensure constraints are also merged during record merging when CSW records are cached.
=> AUS-3800 CSW Record Constraint Fix

src/main/java/org/auscope/portal/core/view/ViewKnownLayerFactory.java, src/main/java/org/auscope/portal/core/view/knownlayer/KnownLayer.java
Replaced KnownLayer's staticLegendUrl field with legendImg.
=> AUS-3890 Static Legends

pom.xml, src/main/java/org/auscope/portal/core/server/controllers/DownloadController.java, src/main/java/org/auscope/portal/core/server/controllers/WMSController.java, src/main/java/org/auscope/portal/core/services/WMSService.java
Added parameter to skip whitelist check on getViaProxy calls.
Added getWMSCapabilitiesViaProxy call.
=> AUS-3914 Custom layers proxy

src/main/java/org/auscope/portal/core/server/controllers/DownloadController.java
Add Content-Type header to proxy calls based on file names where applicable.
=> AUS-3973 Proxy Content-Type

src/main/java/org/auscope/portal/core/server/controllers/CSWSearchController.java, src/main/java/org/auscope/portal/core/services/CSWFilterService.java, src/main/java/org/auscope/portal/core/services/LocalCSWFilterService.java, src/main/java/org/auscope/portal/core/services/csw/CSWServiceItem.java, src/test/java/org/auscope/portal/core/server/controllers/TestCSWSearchController.java, src/test/java/org/auscope/portal/core/services/TestLocalCSWFilterService.java
Allow a custom CSWServiceItem to be used in faceted searches.
https://jira.csiro.au/browse/AUS-3804
=> AUS-3804 Add Registry

src/main/java/org/auscope/portal/core/view/ViewKnownLayerFactory.java, src/main/java/org/auscope/portal/core/view/knownlayer/KnownLayer.java
Added a serverType field to KnownLayer.
=> AUS-3979 TMI Layers

pom.xml, src/main/java/org/auscope/portal/core/cloud/CloudJob.java, src/main/java/org/auscope/portal/core/server/controllers/DownloadController.java, src/main/java/org/auscope/portal/core/server/controllers/OPeNDAPController.java, src/main/java/org/auscope/portal/core/server/controllers/ServiceConfigurationController.java, src/main/java/org/auscope/portal/core/server/controllers/WCSController.java, src/main/java/org/auscope/portal/core/server/controllers/WFSController.java, src/main/java/org/auscope/portal/core/server/controllers/WMSController.java, src/main/java/org/auscope/portal/core/server/http/download/FileUploadBean.java, src/main/java/org/auscope/portal/core/services/WMSService.java, src/main/java/org/auscope/portal/core/services/cloud/FileStagingService.java, src/main/java/org/auscope/portal/core/services/csw/CSWServiceItem.java, src/test/java/org/auscope/portal/core/server/controllers/TestCSWCacheController.java, src/test/java/org/auscope/portal/core/server/controllers/TestDownloadController.java, src/test/java/org/auscope/portal/core/server/controllers/TestWCSController.java, src/test/java/org/auscope/portal/core/server/controllers/TestWfsController.java, src/test/java/org/auscope/portal/core/services/cloud/TestFileStagingService.java, src/test/java/org/auscope/portal/core/services/responses/opendap/TestViewVariableFactory.java, src/test/java/org/auscope/portal/core/test/ByteBufferedServletOutputStream.java, src/test/java/org/auscope/portal/core/test/jmock/ReadableServletOutputStream.java
Mostly involved switching javax.* imports to jakarta.*.
=> Upgrade to Spring Boot 3.1.4.

src/main/java/org/auscope/portal/core/services/CSWCacheService.java
KnownLayers build will be triggered immediately after CSW caching.
=> AUS-4065 Build KnownLayers after CSW caching

src/main/java/org/auscope/portal/core/services/CSWCacheService.java, src/main/java/org/auscope/portal/core/services/KnownLayerService.java, src/test/java/org/auscope/portal/core/server/controllers/TestBaseCSWController.java, src/test/java/org/auscope/portal/core/services/KnownLayerServiceTest.java, src/test/java/org/auscope/portal/core/services/TestCSWCacheService.java, src/test/java/org/auscope/portal/core/services/TestKnownLayerService.java
Modified how CSWCacheService and KnownLayerService are autowired to allow for testing.
=> AUS-4077 Rewire Services

.github/coverage/jacoco.csv, src/main/java/org/auscope/portal/core/services/ElasticsearchService.java
Type of Criteria used for searching may be either expression or contains depending on the search text.
Try/catch blocks added to criteria creation.
=> AUS-4107 Search Robustness

src/main/java/org/auscope/portal/core/services/CSWCacheService.java, src/main/java/org/auscope/portal/core/services/responses/csw/CSWGeographicBoundingBox.java, src/main/java/org/auscope/portal/core/services/responses/csw/CSWGeographicElement.java, src/main/java/org/auscope/portal/core/view/ViewCSWRecordFactory.java
Caused by CSWCacheService not merging coordinate BBOXes
=> AUS-4228 Fix WMS requesting tiles outside bounds

src/main/java/org/auscope/portal/core/server/controllers/DownloadController.java, src/main/java/org/auscope/portal/core/server/http/HttpServiceCaller.java
HttpServiceCaller now attaches error code to IOException
=> AUS-4061 AusPASS Errors

src/main/java/org/auscope/portal/core/services/CSWCacheService.java, src/main/java/org/auscope/portal/core/services/ElasticsearchService.java
Stop locally cached CSW records from disappearing when a CSW registry is unresponsive.
=> AUS-4247 CSW Records Disappearing After Update

src/main/java/org/auscope/portal/core/services/responses/csw/CSWRecord.java
Fixed issue where CSWRecords with null OnlineResources would cause the KnownLayers build to fail silently.
=> AUS4249 KnownLayers Build Failing

src/main/java/org/auscope/portal/core/services/ElasticsearchService.java
Refactored code so combinations of search filters work better.
=> AUS-4297 Search Filter Issues

src/main/java/org/auscope/portal/core/server/controllers/ElasticsearchController.java, src/main/java/org/auscope/portal/core/services/ElasticsearchService.java, src/test/java/org/auscope/portal/core/services/TestElasticsearchService.java
=> AUS-4367 Add Polygon Search

src/main/java/org/auscope/portal/core/services/ElasticsearchService.java, src/main/java/org/auscope/portal/core/services/responses/csw/CSWRecordTransformer.java, src/main/resources/org/auscope/portal/core/test/responses/csw/cswRecordResponse_largeDenominator.xml, src/test/java/org/auscope/portal/core/services/TestElasticsearchService.java, src/test/java/org/auscope/portal/core/services/responses/csw/TestCSWRecordTransformer.java
- Springboot's elasticsearch code was crashing if the scale denominator was a large Double
=> AUS-4375 Fix for large scale denominator problem
