AuScope/portal-core

src/main/webapp/portal-core/js/portal/widgets/grid/plugin/InlineContextMenu.js
src/main/webapp/portal-core/js/portal/widgets/grid/plugin/RowExpanderContainer.js
src/main/webapp/portal-core/js/portal/widgets/panel/BaseRecordPanel.js

I changed some "this" to "me" for optimisation. Had an issue with closure scope of "this" not working as I expected, then instead of reverting that I decided to pass in the object that needed to be updated (grid) rather than relying on the closure scope to get the reference to the grid. It seems simpler and neater to me. We've tested in our CI environment and it appears to all work fine.

Gpt 57   clicking on a layer causes javascript error which stops layers from working

---

src/main/webapp/portal-core/js/portal/events/AppEvents.js
src/main/webapp/portal-core/js/portal/layer/filterer/BaseFilterForm.js
src/main/webapp/portal-core/js/portal/widgets/grid/plugin/RowExpanderContainer.js
src/main/webapp/portal-core/js/portal/widgets/panel/BaseRecordPanel.js
src/main/webapp/portal-core/js/portal/widgets/panel/CommonBaseRecordPanel.js

Fixed a memory leak that I'm 90% sure caused the bug at Geoscience where dragging and dropping to reorder the layers in the Active Layers panel would eventually stop working. Although this was reported in GA portal, its in core code and needed to be fixed.
I've left debug in AppEvents.js since this bug could crop up in other places (though couldn't find on first look). I'm planning to add a debug library so can set the logging level and will be sending another PR soonish.
UPDATE - that debug library was looking like too much work (uses require.js) so have just commented out the console.logs.

Gpt 73 active layers stop reordering for auscope

---

src/main/java/org/auscope/portal/core/services/responses/wms/GetCapabilitiesWMSLayer_1_3_0.java
src/main/webapp/portal-core/js/portal/events/AppEvents.js
src/main/webapp/portal-core/js/portal/layer/LayerStore.js
src/main/webapp/portal-core/js/portal/layer/legend/wms/WMSLegend.js
src/main/webapp/portal-core/js/portal/layer/legend/wms/WMSLegendForm.js
src/main/webapp/portal-core/js/portal/layer/renderer/wfs/FeatureWithMapRenderer.js
src/main/webapp/portal-core/js/portal/layer/renderer/wms/DisjunctionLayerRenderer.js
src/main/webapp/portal-core/js/portal/layer/renderer/wms/LayerRenderer.js
src/main/webapp/portal-core/js/portal/widgets/panel/BaseRecordPanel.js
src/main/webapp/portal-core/js/portal/widgets/panel/LayerPanel.js

* Previously portal-core was generating a hard-coded URL to getLegendGraphic.  However sometimes the LegendUrl in the getCapabilities was different.  So now LegendUrl is hit in the first place
* The code behind GetCapabilities was updated.  Previously GetCapabilitiesWMSLayer_1_3_0 was building the XML node structure for EVERY node for every layer.  I changed it to only build the node for the element that was request (eg. 'Legend').  This took the time to render the LegendUrl from 70 secs to 13 for the example I was looking at (Populated Places).
* For some reason (and perhaps something to investigate separately), the gis server at GA is returning truncated (width) legend graphics.  So if the graphic is being returned with a .../...?REQUEST=GetLegendGraphic then a WIDTH=100 is being sent …

Gpt 80 display legend url for WMS

---

pom.xml
src/main/java/org/auscope/portal/core/services/cloud/CloudComputeService.java
src/main/java/org/auscope/portal/core/services/cloud/SimpleEC2Client.java
src/main/java/org/auscope/portal/core/services/namespaces/AWSEC2NamespaceContext.java
src/test/java/org/auscope/portal/core/services/cloud/TestSimpleEC2Client.java
src/test/resources/org/auscope/portal/core/aws/getconsoleoutput-response-success.xml
src/test/resources/org/auscope/portal/core/aws/modifyinstanceattribute-response-failure.xml
src/test/resources/org/auscope/portal/core/aws/modifyinstanceattribute-response-success.xml

Added EC2 support to the cloud compute service. There was a need to handroll our own EC2 client due to an inability to reconcile various jackson dependencies between our spring-oauth2-security-client (+ others) and the official AWS Java EC2 SDK. We were also unable to use the JClouds API for some functionality in AWS which basically left us with implementing our own SimpleEC2Client.
Any portals using CloudComputeService can continue to operate without changing any constructor arguments.
See https://jira.csiro.au/browse/ANVGL-3 for the full notes

ANVGL-3 AWS EC2 Support for CloudComputeService

---

pom.xml
src/main/java/org/auscope/portal/core/test/PortalTestClass.java
src/main/java/org/auscope/portal/core/util/DOMUtil.java

compileXPathExpr (when not namespace aware) will offload to any given XPath provider. The whole point of this class is to make for a consistent provider.
We fix this by making the XPathFactory instantiating consistent with the namespace aware method.

AUS-2607 Fixed compileXPathExpr using undefined provider

---

src/main/java/org/auscope/portal/core/services/responses/csw/CSWRecord.java
src/main/java/org/auscope/portal/core/services/responses/csw/CSWRecordTransformer.java
src/main/java/org/auscope/portal/core/view/ViewCSWRecordFactory.java
src/main/webapp/portal-core/js/portal/csw/CSWRecord.js
src/main/webapp/portal-core/js/portal/layer/Layer.js

This change allows the portals to differentiate between a service (ie a parent layer) and a dataset. 
For example, when displaying available layers from a getCapabilities request we use the service URL which returns all the layers, not just the layer of interest. getCapabilities does not allow a layername parameter like getMap does and I could not figure out any other way to interrogate the CSW record to learn whether it is a service.

Gpt 82 add service flag to csw record

---

src/main/java/org/auscope/portal/core/view/knownlayer/KnownLayer.java
src/main/webapp/portal-core/js/portal/knownlayer/KnownLayer.js

The order of layers can now be specified in alphanumerical format, e.g - 
<property name="order" value="1_Geological Survey of Western Australia_5"/>

Alphanumerical layer ordering

---

src/main/webapp/portal-core/js/portal/widgets/grid/plugin/RowExpanderContainer.js

There is a rare JS error that can occur with the RowExpanderContainer that is related to the regeneration of the internal containers.
Basically if there is a tooltip open and the panel is regenerated (you can trigger this on rare occasions by expanding a group/row with an open tooltip) you'll get a nasty JS error during component destruction.
There's not a whole lot we can do to stop it, we can however recover somewhat gracefully...
See: https://jira.csiro.au/browse/AUS-2608

AUS-2608 Fixed a JS error that can occur with orphaned tooltips

---

src/main/java/org/auscope/portal/core/test/AssertViewUtility.java

The unit test utility class for comparing ModelMaps is pretty bad at telling you WHERE in the model maps the difference lies. This is a minor improvement to make it a bit easier to figure out what's going wrong.

Improved assertion errors when failing unit tests

---

src/main/java/org/auscope/portal/core/services/responses/wms/GetCapabilitiesWMSLayer_1_1_1.java
src/main/java/org/auscope/portal/core/services/responses/wms/GetCapabilitiesWMSLayer_1_3_0.java

As per the getCapabilities specs for both 1.1.1 and 1.3.0 WMS services, MetadataURL
contains an OnlineResource element that contains our MetadataURL.
I am keeping the ability to grap a text value straight out of the MetadataURL element if not found
in the proper location.

GPT-122 more flexible location of metadataURL

---

src/main/webapp/portal-core/js/portal/map/openlayers/OpenLayersMap.js

Does not fix issues with conjunction layers (for example, 1:1M Surface Geology - contacts, faults, marker beds, can't query on all layers within the conjunction)

GPT-133 fixed queries for disjunction layers

---

src/main/webapp/portal-core/js/portal/widgets/panel/CommonBaseRecordPanel.js

added the ability to override the service info and map extent icons if the portal implementation (eg Geoscience Portal) requires different icons

GPT-108 allow override info and extent icons

---

src/main/webapp/portal-core/jsimports-openlayers.htm

Previous OpenLayers upgrade to 2.13.1 missed a few img references.

AUS-2613 Fixed img references to old openlayers

---

src/main/java/org/auscope/portal/core/services/responses/wcs/AxisDescriptionImpl.java
src/main/java/org/auscope/portal/core/services/responses/wcs/DescribeCoverageRecord.java
src/main/java/org/auscope/portal/core/services/responses/wcs/Interval.java
src/main/java/org/auscope/portal/core/services/responses/wcs/RangeSetImpl.java
src/main/java/org/auscope/portal/core/services/responses/wcs/SimpleEnvelope.java
src/main/java/org/auscope/portal/core/services/responses/wcs/SpatialDomain.java
src/main/java/org/auscope/portal/core/services/responses/wcs/ValueEnumTypeFactory.java

The WCS DescribeCoverageRecord currently manages all of its own XPath libraries which is a bit silly when we have DOMUtil to do that for us. Under certain environments this can cause all sorts of headaches.
The fix is to replace all the manual XPath generation with calls to DOMUtil

AUS-2614 Offloaded WCS XPath creation to DOMUtil

---

src/main/java/org/auscope/portal/core/server/http/download/DownloadTracker.java
src/main/java/org/auscope/portal/core/server/http/download/ServiceDownloadManager.java
src/main/java/org/auscope/portal/core/util/FileIOUtil.java
src/main/java/org/auscope/portal/core/util/MimeUtil.java
src/main/webapp/portal-core/js/portal/layer/downloader/wfs/KLWFSDownloader.js

The Download code in AuScope essentially makes a series of HTTP requests and bundles the results into a ZIP file, appending an arbitrary XML file extension.
This obviously doesn't work well with CSV downloads (supported by some WFS) so this PR attempts to add an override where the file extension can be forced at the controller level.

AUS-2609 Downloader to better support variable file extensions

---

src/main/java/org/auscope/portal/core/util/FileIOUtil.java

writeResponseToZip will fail to generate an extension based on ContentType if the first request has an error. This PR looks for the first successful response to look for content type file extension hints.

AUS-2609 Made content-type parsing more robust

---

src/main/java/org/auscope/portal/core/server/controllers/BasePortalController.java
src/main/java/org/auscope/portal/core/services/BaseWFSService.java
src/main/java/org/auscope/portal/core/services/responses/wfs/WFSResponse.java
src/main/webapp/portal-core/js/portal/layer/renderer/wfs/FeatureRenderer.js
src/main/webapp/portal-core/js/portal/layer/renderer/wfs/FeatureWithMapRenderer.js
src/main/webapp/portal-core/js/portal/layer/renderer/wfs/GMLParser.js
src/main/webapp/portal-core/jsimports.htm
src/test/java/org/auscope/portal/core/services/TestBaseWFSService.java

An old hangover from earlier portals is the WFS -> GML -> KML -> OpenLayers Primitives pathway for WFS responses.
It's problematic because
a) It's a whole lot of CPU/Bandwidth wasted
b) It stuffs us around when you consider non GML responses from WFS (eg CSV)
The actual portal controllers will need to strip out the KML generation code.

AUS-2615 Deprecated KMLParser for GMLParser

---

src/main/webapp/portal-core/js/portal/widgets/panel/FilterPanel.js

GA Portal (and other portals, if they use the mechanism) now supply its own menu items so adding Legend by default is not suitable (GA Portal has a legend control in the active layers panel). Furthermore, if no options are left then we hide the Options drop down.

GPT-72 removed legend, removed options if no options present

---

src/main/webapp/portal-core/js/ext-5.1.1/build/index.html
src/main/webapp/portal-core/jsimports-openlayers.htm

Scripts need to be loaded over https or the main site can not be https (results in browser error message)

Scripts need to be loaded over https

---

src/main/java/org/auscope/portal/core/services/methodmakers/WFSGetFeatureMethodMaker.java
src/main/java/org/auscope/portal/core/services/methodmakers/filter/SimpleBBoxFilter.java

GPT-74 introduced some changes to the SimpleBBOXFilter and WFSGetFeatureMethodMaker to better support ArcGIS. Namely:
Forcing BBOX filters to filter on property name "shape"
Forcing wfs:Query elements to have an srsName starting with "urn"
These seemed innocuous at the time but have since started causing issues with a number of WFS feature types (Yilgarn/NVCL etc).
We will need to revert these changes BUT we also need to provide GA with a means to go forward.

AUS-2617 Reverting GPT-74

---

src/main/java/org/auscope/portal/core/util/FileIOUtil.java
src/test/java/org/auscope/portal/core/server/http/download/TestDownloadTracker.java

The FileIOUtil decomposes responses in the form
{success:true, data:{gml:'txt'}}
This update makes it so the "gml" attribute of "data" can take any name.

AUS-2615 JSON data object parsing more flexible

---

src/main/webapp/portal-core/js/portal/events/AppEvents.js

Checks whether args.layer exists before proceeding with storing the application state.

GPT-73 - Putting extra condition into broadcast function that handles layers

---

src/main/webapp/portal-core/js/openlayers-patches/2.13.1/OpenLayers_patch.js
src/main/webapp/portal-core/jsimports.htm

This patch fixes a problem with showing some base layers, eg Google Streets,
when the map is first loaded
Not sure whether I followed the standard or best practices for naming patch files as there wasn't much to base it on... let me know if you have any suggestions. My thinking was that any other patches could go in the same file so it has a generic name, and it resides in a directory named after the OL version it is patching.

Openlayers patch to fix problem with Gmaps v3 API

---

src/main/webapp/portal-core/js/portal/layer/renderer/wfs/GMLParser.js

... is not cross-browser. It seems that the standard way to do this is like getElementsByTagNameNS("*", "posList"). 
I wanted something like getElementsByTagNameNS("gml", "posList") but that didn't work either.

GPT-182 getElementByTagName

---

src/main/java/org/auscope/portal/core/services/cloud/CloudComputeServiceAws.java

Needed to support the fix for ANVGL-80, allowing per-user (per-job as far as portal-core is concerned) keypairs.
In the AWS implementation (CloudComputeServiceAws) we need to check for a keypair set on the job instance before falling back to the current default of using the one on the CCS instance.

Use keypair from CloudJob before default to one from CCS

---

src/main/java/org/auscope/portal/core/cloud/CloudFileOwner.java
src/main/java/org/auscope/portal/core/cloud/CloudJob.java
src/main/java/org/auscope/portal/core/services/cloud/CloudStorageService.java

Dynamic bucket name creation responsiblity really belongs as part of the CloudFileOwner.
This will be backwards compatible for "old style" static bucket name. The only "dynamic" bucket name stuff is in ANVGL and that's already got a pull open to deal with this change.

ANVGL-82 Moved bucket names to CloudFileOwner

---

src/main/webapp/portal-core/js/openlayers-patches/2.13.1/OpenLayers_patch.js

The openlayers patch (currently) throws an error if OpenLayers is not defined (which can happen on pages without a map instance loaded). There is already a check for if OpenLayers exists it's just the most recent additions to this file were not put inside of this check (which was a minor oversight).
This PR changes no functionality, it just moves the remaining patch code inside of the "if OpenLayers" check to avoid JS errors.

Fixed patch throwing JS errors if OL not present

---

src/main/java/org/auscope/portal/core/services/cloud/CloudComputeService.java
src/main/java/org/auscope/portal/core/services/cloud/CloudComputeServiceAws.java
src/main/java/org/auscope/portal/core/services/cloud/CloudComputeServiceNectar.java
src/test/java/org/auscope/portal/core/services/cloud/TestCloudComputeService.java
src/test/java/org/auscope/portal/core/services/cloud/TestCloudComputeServiceAws.java

Added a getJobStatus method to the CloudComputeService base. This returns a very low level status on a job VM which can be used for reporting accurate information to the end user about the status of their compute jobs.
Unit tests for both AWS/NeCTAR implementations are also included.
Changes are backwards compatible.

ANVGL-70 Added VM status lookups to CloudComputeService

---

src/main/java/org/auscope/portal/core/view/ViewKnownLayerFactory.java
src/main/java/org/auscope/portal/core/view/knownlayer/KnownLayer.java
src/main/webapp/portal-core/js/portal/knownlayer/KnownLayer.js
src/main/webapp/portal-core/js/portal/map/openlayers/primitives/WMSOverlay.js

This feature allows known layers to override the WMS Overlay check for URL length that creates a POST request in the SLD_BODY is too long. This is gone for services like ArcGIS that don't allow POSTs made to WMS. 
forceWMSGet was chosen as opposed to denoting what service the known layer was pointing to because layers like mt:MineralTenement point to a range of different service end points, not all of which are ArcGIS.

GPT-152 Force WMS Get

---

src/main/webapp/portal-core/js/portal/layer/renderer/wfs/FeatureRenderer.js
src/main/webapp/portal-core/js/portal/layer/renderer/wfs/FeatureWithMapRenderer.js
src/main/webapp/portal-core/js/portal/layer/renderer/wfs/GMLParser.js

We are currently reporting on number of geometry primitives returned as our "feature count". This doesn't work when you have feature types with > 1 geometry.
Changed feature count reporting to use the feature count as reported by the WFS response.

Fixed feature count being reported as geometry count

---

src/main/java/org/auscope/portal/core/services/cloud/CloudComputeServiceAws.java
src/test/java/org/auscope/portal/core/services/cloud/TestCloudComputeServiceAws.java

AWS is a bit funny about describe instance status requests on a newly requested VM. I've made the code a little bit more robust by ensuring that "newly submitted" VM's don't get a remote request, instead they are assumed to be Pending.
Change is backwards compatible.

ANVGL-112 Made status checks delay for new VMs

---

src/main/java/org/auscope/portal/core/view/knownlayer/OGCSelector.java
src/main/java/org/auscope/portal/core/view/knownlayer/WMSWFSSelector.java

New selector to take account of when you want a WMS with a WFS, but the featureType and layerName does not match. Should be extended in future iterations with relatedFeatureTypes and serviceEndPoints to match behaviour of other selectors, but have cut those out for now for simplicity.

GPT-104 New selector for WMS and WFS

---

src/main/webapp/portal-core/js/portal/widgets/window/PermanentLinkWindow.js

This is a change to the Permanent Link window. It adds a button to offer the user an alternative and more intuitive way to copy the permanent link text to the clipboard.
The users asked for this.
If you click out of the field it is not selected anymore and they didn't know how to select all easily.
I know they could just do Ctrl+a or slow three-click (to select all) and then Ctrl+c (to copy) but this button adds to useability so I dont have a huge problem with implementing it. CSIRO guys might want to push back on this, I'm half inclined to insist on user training as well but yknow.

GPT-181 added button

---

src/main/webapp/portal-core/js/portal/widgets/grid/plugin/RowExpanderContainer.js

This is two improvements for the RowExpanderContainer
1) If the underlying data model doesn't have an "id" field the current implementation will crash. This adds a configurable "recordIDProperty" to specify an alternate ID.
2) if the underlying store is cleared then the internal recordStatus cache will become very stale leading to JS errors. This adds a "proper" cleaning function for this circumstance.
Changes are backwards compatible.

ANVGL-116 Support for stores that clear or have no id

---

src/main/webapp/portal-core/js/openlayers-patches/2.13.1/OpenLayers_patch.js
src/main/webapp/portal-core/js/portal/map/openlayers/OpenLayersMap.js

When using the "select data" control in OpenLayers, the rubber bound bounding box appears "underneath" any WMS layers making it rather useless.
Similarly the map highlights (from magnifying glass links) appear at the bottom of the z-index stack.
This patches an OpenLayers bug for the first problem and creates a forced re-ordering of our highlight layers for the second.

ANVGL-106 Fixed some z-index bugs with "top level" layers

---

src/main/webapp/portal-core/js/portal/layer/legend/wms/WMSLegend.js

The eternally frustrating situation of compatibility between ArcGIS and Geoserver.
Difference in behaviour encountered here:
1. If an SLD is to be applied to an ArcGIS GetLegendGraphic request, the STYLE parameter must match the UserStyle/Name in the SLD of the style you wish to apply.
2. For a Geoserver GetLegendGraphic, the STYLE parameter must match a style that has been predefined server side, the SLD is ignored if this parameter is used.
3. This was not detected, as by serendipity most of the STYLE parameters in the SLDs we were sending to Geoserver matched their predefined styles that were configured server side ("portal-style").
4. So to get around this, we check if its an ArcGIS service we're using.

Another hacky check for ArcGIS

---

src/main/java/org/auscope/portal/core/services/methodmakers/CSWMethodMakerGetDataRecords.java
src/test/java/org/auscope/portal/core/services/methodmakers/TestCSWMethodMakerGetDataRecords.java

ArcGIS Server Geoportal does not accept csw:IsoRecord as a value for the outputSchema parameter. Must use http://www.isotc211.org/2005/gmd to get ISO metadata. Tested against GeoNetwork and it works.

GPT-169 Change outputSchema

---

src/main/java/org/auscope/portal/core/services/cloud/CloudStorageService.java
src/test/java/org/auscope/portal/core/services/cloud/TestCloudStorageService.java

Currently any non "file" objects in cloud storage under a job prefix will cause exceptions to be thrown. This usually won't manifest unless a third party tool is also writing to job storage areas.
This will be backwards compatible.

ANVGL-130 Fixed folders in storage crashing file listing

---

src/main/webapp/portal-core/js/portal/layer/renderer/wms/LayerRenderer.js

Some ArcGIS services do not like the XML declaration in the SLD_BODY
parameter, so we must leave it off. Therefore the portal needs to
check whether there is either a <?xml or <StyledLayerDescriptor partial
tag. We also apply the filterer parameters here to the SLD proxy request,
following what is done in FeatureWithMapRenderer.js

GPT-236 Check for SLD tag and apply filter params to SLD request

---

src/main/webapp/portal-core/js/portal/widgets/panel/CSWMetadataPanel.js
src/main/webapp/portal-core/js/portal/widgets/panel/OnlineResourcesPanel.js

GPT-148 meant to populate the CSW metadata panel with Download links, but this was causing issues with the online resources panels for featured layers. I reversed that change, while removing the online resources panel unless there are records found.

GPT-255  remove downloads from service information dialog aus

---

src/main/webapp/portal-core/js/portal/layer/downloader/coverage/OPeNDAPDownloader.js
src/main/webapp/portal-core/js/portal/layer/downloader/coverage/WCSDownloader.js
src/main/webapp/portal-core/js/portal/layer/downloader/wfs/KLWFSDownloader.js
src/main/webapp/portal-core/js/portal/layer/legend/wms/WMSLegend.js
src/main/webapp/portal-core/js/portal/layer/querier/coverage/WCSQuerier.js
src/main/webapp/portal-core/js/portal/layer/querier/wfs/featuresources/WFSFeatureByPropertySource.js
src/main/webapp/portal-core/js/portal/layer/querier/wfs/featuresources/WFSFeatureSource.js
src/main/webapp/portal-core/js/portal/layer/renderer/wfs/FeatureDownloadManager.js
src/main/webapp/portal-core/js/portal/util/Ajax.js
src/main/webapp/portal-core/js/portal/widgets/panel/CSWFilterFormPanel.js
src/main/webapp/portal-core/jsimports.jsp

Added a wrapper around Ext.Ajax.request that specialises it to the "standard" JSON format returned by all JSON controllers. Updated the few instances in portal-core where appropriate.
This change does not require a migration to portal.util.Ajax.request from Ext.Ajax. It's just a convenience method to reduce Ajax boilerplate.

Added standardised JSON Ajax wrapper

---

src/main/webapp/portal-core/js/portal/layer/querier/wms/GeotransectQuerier.js

Onshore Seismic Surveys endpoint has been updated. The dataset
contains the correct URLs and we no longer need to hardcode.
Please update your metadata catalogs to reflect the new endpoint.
http://services.ga.gov.au/gis/services/Onshore_Seismic_Surveys/MapServer/WMSServer

GPT-253 Remove hardcoding of URL

---

src/main/webapp/portal-core/js/portal/layer/filterer/Filterer.js

A null bounding box will cause a JS error when getMercatorCompatibleParameters is called. This is unnecessary and causes issues in some edge cases.
Changed to make the parameter generation a little more robust w.r.t. null values.

Fixed null bbox breaking getMercatorCompatibleParameters

---

src/main/webapp/portal-core/js/portal/layer/renderer/wms/LayerRenderer.js

If the SLD response is invalid, default to rendering the native-styled layer from the service.
This change to behaviour will differ from FeatureWithMapRenderer, which fails to render the layer if the SLD is invalid. We have chosen to return an empty SLD for our Scanned Maps Layers if no filter parameters are applied, and therefore use the styling supplied by the service.

Render map if SLD invalid

---

src/main/webapp/portal-core/jsimports-openlayers.jsp

Added a simple googleKey placeholder to the gmap API. If not available, spring will replace it with empty string which still works fine with gmap.

ANVGL-146 Added a googlemap key placeholder

---

src/main/webapp/portal-core/js/portal/layer/Layer.js
src/main/webapp/portal-core/js/portal/widgets/layout/AccordianDefault.js
src/main/webapp/portal-core/js/portal/widgets/panel/BaseRecordPanel.js
src/main/webapp/portal-core/js/portal/widgets/panel/CommonBaseRecordPanel.js
src/main/webapp/portal-core/js/portal/widgets/panel/RecordGroupPanel.js
src/main/webapp/portal-core/js/portal/widgets/panel/RecordPanel.js
src/main/webapp/portal-core/js/portal/widgets/panel/RecordRowPanel.js
src/main/webapp/portal-core/js/portal/widgets/plugins/ClickableImage.js
src/main/webapp/portal-core/js/portal/widgets/plugins/CollapsedAccordianLayout.js
src/main/webapp/portal-core/jsimports.jsp

This contains breaking changes to extensions to CommonBaseRecordPanel/BaseRecordPanel. 
The current implementation of the rowexpandercontainer is a mess due to ExtJS 5 blowing away all DOM elements on group/row collapse. This is our attempt to have something identical in functionality but without any of the flakiness.
The approach has been to abandon Ext.grid.Panel in favour of several nested Ext.panel.Panel objects in a modified accordian layout. The nested accordian panels emulate the groups/rows/rowexpander panels.
The new implementation is more or less the same as the old Ext.grid.Panel widget. It however does NOT emulate the original configuration API identically so there are some minor breaking changes.

AUS-2685 Full replacement of BaseRecordPanel Ext.grid.Panel implementation

---

src/main/webapp/portal-core/js/portal/widgets/panel/RecordPanel.js

Filtering any panel with a large number of records is incredibly slow, this patch disables superfluous layouts during the filter operation.

AUS-2701 Improved RecordPanel filter performance

---

src/main/webapp/portal-core/js/portal/widgets/panel/BaseRecordPanel.js

The current child panel generation is quirky due to (now false) expectations of the underlying filter panel being repeatedly deleted. This change simplifies these assumptions and removes some buggy edge cases.

AUS-2622 Simplified child panel generation.

---

src/main/java/org/auscope/portal/core/services/responses/wms/GetCapabilitiesWMSLayer_1_3_0.java

There were some naughty direct XPath factory calls in GetCapabilitiesWMSLayer_1_3_0 that can cause issues in some environments. This PR simply replaces them with the preferred DOMUtil method of creating XPath expressions.

Replaced direct XPath generation with DOMUtil references

---

src/main/webapp/portal-core/js/portal/map/openlayers/OpenLayersMap.js

Fix for Earth resource mine information window does not appear when map is clicked.
Introduced by GPT-133. Need to apply __getDomain() to both sides of
equivalence test.

AUS-2634: Fix for Earth resource mine information window does not appear

---

src/main/webapp/portal-core/js/portal/layer/Layer.js

The KML layer, unlike most other layers, leaves 'onlineResources' as
'null', so an additional check is needed.

AUS-2639: UI bug when adding KML layer

---

src/main/webapp/portal-core/js/portal/layer/filterer/forms/WMSLayerFilterForm.js

Simple change to stop layers being added to map when the opacity slider is moved. Credit to Josh who did the work on this, I just tested it and made sure it worked.

ANVGL-101: Opacity slider change adding layer to map

---

src/main/java/org/auscope/portal/core/cloud/ComputeType.java
src/main/java/org/auscope/portal/core/services/cloud/CloudComputeServiceAws.java

Fixes ANVGL-157: Added X1 machine types and change c3/m3 to c4/m4.

Anvgl 157: Add X1 and other current AWS machine types

---

src/main/java/org/auscope/portal/core/services/cloud/CloudComputeServiceAws.java
src/main/java/org/auscope/portal/core/view/JSONView.java

Now returning "pending" when computeInstanceId is not set in getJobStatus(). Also writing debug message to log.
Saving JSON content to local variable before writing to response to make debugging easier.

Better handling of unset computeInstanceId in job status query on AWS.

---

src/main/java/org/auscope/portal/core/services/cloud/CloudComputeServiceAws.java

Wrap any AmazonServiceException on a RunInstances request in a PortalServiceException to re-throw, matching the throws clause on executeJob. ANVGL is catching PSEs, not other exceptions.

Wrap ASE in PSE on RunInstances request

---

src/main/webapp/portal-core/js/portal/widgets/panel/CSWRecordPanel.js

Referencing CSWRecordPanel using an xtype is currently not possible. This adds a widget alias to fix that.

ANVGL-13 Added alias to CSWRecordPanel

---

src/main/webapp/portal-core/js/portal/widgets/panel/recordpanel/AbstractChild.js
src/main/webapp/portal-core/js/portal/widgets/panel/recordpanel/RecordPanel.js

Added an emptyText config option to RecordPanel that supports HTML. The emptyText (if configured) will show whenever the underlying record store is empty.

ANVGL-13 Added empty text support to RecordPanel

---

src/main/webapp/portal-core/js/portal/widgets/panel/BaseRecordPanel.js

BaseRecordPanel can now be further extended by child classes by allowing all constructor config options to be overridable by default.

ANVGL-13 Made config options overridable

---

src/main/webapp/portal-core/js/portal/widgets/panel/recordpanel/RecordPanel.js

Added a "reorder" event and also made the child panel generator support rows that do not have a child. This will prevent the row from expanding on click.

ANVGL-13 Added reorder event and support for no children

---

src/main/webapp/portal-core/js/portal/layer/Layer.js

The layer should've always had this metadata, the question of whether the info should be removed at the source (CSWRecord/KnownLayer) is another matter that will require some refactoring.

ANVGL-13 Duplicated visibility flags in active layer

---

src/main/java/org/auscope/portal/core/view/ViewCSWRecordFactory.java
src/main/java/org/auscope/portal/core/view/ViewKnownLayerFactory.java
src/main/java/org/auscope/portal/core/view/knownlayer/KnownLayer.java
src/main/webapp/portal-core/js/portal/knownlayer/KnownLayer.js
src/main/webapp/portal-core/js/portal/layer/legend/wms/WMSLegend.js
src/main/webapp/portal-core/js/portal/layer/legend/wms/WMSLegendForm.js
src/main/webapp/portal-core/js/portal/layer/querier/Querier.js
src/main/webapp/portal-core/js/portal/layer/querier/wfs/WFSWithMapQuerier.js
src/main/webapp/portal-core/js/portal/map/openlayers/primitives/WMSOverlay.js
src/test/java/org/auscope/portal/core/view/TestViewCSWRecordFactory.java

Uses the applicationProfile field of ISO metadata to determine whether a WMS service is provided by Esri. Format of the applicationProfile is specified by USGIN at the link below 
http://usgin.github.io/usginspecs/USGIN_ISO_Metadata.htm
>  applicationProfile is required if the CI_OnlineResource/linkage does not connect to a web page, and another software application is needed to use the indicated file resource. The applicationProfile character string should specify the software using the following recommended syntax: “vendor:application name/application version”, e.g. “Microsoft:Word/2007”

GPT-152 QLD Tenements and working with ArcGIS Server

---

src/main/webapp/portal-core/js/portal/map/openlayers/OpenLayersMap.js
src/main/webapp/portal-core/js/portal/map/openlayers/PrimitiveManager.js

All of our primitive managers (one per layer) are being generated at page load. This is generating a ton of unnecessary OpenLayer vector layers and causing performance issues for large registries.
This fixes the problem by lazy instantiation of the vector layer

AUS-2756 Made prim managers lazily generate layers

---

src/main/webapp/portal-core/js/portal/map/openlayers/OpenLayersMap.js

When refreshing AusGIN, cached layers are loaded and the absence of a highlightLayer causes failure.

Fix problem where highlight layer does not exist

---

pom.xml
src/main/java/org/auscope/portal/core/cloud/CloudJob.java
src/main/java/org/auscope/portal/core/services/cloud/CloudComputeServiceAws.java
src/main/java/org/auscope/portal/core/services/cloud/CloudComputeServiceNectar.java
src/main/java/org/auscope/portal/core/services/cloud/CloudStorageService.java
src/main/java/org/auscope/portal/core/services/cloud/STSRequirement.java
src/test/java/org/auscope/portal/core/services/cloud/TestCloudComputeService.java
src/test/java/org/auscope/portal/core/services/cloud/TestCloudComputeServiceAws.java
src/test/java/org/auscope/portal/core/services/cloud/TestCloudStorageService.java

Following broad testing with the cloud compute/storage services against the latest NeCTAR Openstack deployment we discovered a number of deficiencies. The following changes have been made (some of them breaking backwards compatibility for users of the CloudComputeService/CloudStorageService)
* Replaced requireSTS boolean with a more flexible STSRequirement enum
* Stripped out region by region submission in the CloudComputeServiceNectar due to missing support at the NeCTAR end for enumerating regions
* Fixed region specific submissions for OpenStack cloud providers (regionName has only worked with AWS up until now)

VGL-171 Cloud Compute/Storage NeCTAR Fixes

---

src/main/webapp/portal-core/js/portal/layer/Layer.js

Added the visible flag to the model for Layer, such that a store update event would change the icon in the ActiveLayerPanel. This means there is a duplication of visible flags in the Layer class, but I left the original there in case othe rportals depend on that flag.
The visible flag outside the model may be a candidate for deprecation, as noted in comments.

Add visibile to Layer model

---

src/main/webapp/portal-core/js/portal/widgets/panel/BaseRecordPanel.js
src/main/webapp/portal-core/js/portal/widgets/panel/recordpanel/RecordPanel.js

Added an optional (upfront) performance improvement for record panels with many rows with children.
When activated all child filter panels will NOT be rendered, they will be injected during the beforeexpand event.

AUS-2770 Added lazy loading of child panels

---

src/main/webapp/portal-core/js/portal/layer/renderer/wms/LayerRenderer.js

WMS Opacity is checked in numerous places in the renderers and filter forms - need to refactor the behaviour for handling opacity.

Check for opacity in rendering of layer

---

src/main/webapp/portal-core/js/portal/map/openlayers/FeatureWithLocationHandler.js

The "mouseDragFlag" was initially set to "true". This meant that any incoming "click" events are not acted upon, until the first "mousedown" then "mouseup" where distance < 5. This doesn't occur readily.
By setting it to "false", incoming "click" events are handled. 
I have checked that there is no regression of AUS-2592.5, i.e. dragging the map does not invoke a query.
I have tested this on IE, Chrome & Firefox.

AUS-2762: Fix to problem where layer query pop-up fails to appear

---

src/main/java/org/auscope/portal/core/services/cloud/CloudComputeServiceNectar.java
src/test/java/org/auscope/portal/core/services/cloud/TestCloudComputeService.java

JClouds can occasionally return a null metadata object for requests to NeCTAR VM's for metadata. This PR fixes this.

VGL-200 Stopped NPE With JClouds NeCTAR Status Check

---

src/main/java/org/auscope/portal/core/services/cloud/CloudStorageService.java
src/main/java/org/auscope/portal/core/services/cloud/CloudStorageServiceJClouds.java
src/test/java/org/auscope/portal/core/services/cloud/TestCloudStorageService.java

Currently the CloudStorageService base class only supports uploads to the cloud directly from java.io.File objects. This PR adds support for inputstream sources too.

VGLOPS-13 Support for file uploads from non File sources

---

src/main/webapp/portal-core/js/portal/widgets/plugins/HeaderIcons.js
src/main/webapp/portal-core/jsimports.jsp

Created a plugin that can be applied to all Ext.panel.Panel variants. Allows a set of icons to be added before/after the header text. These icons can handle click events/tooltips.

VGLOPS-7 Support for headericons plugin

---

src/main/webapp/portal-core/js/portal/widgets/panel/CSWMetadataPanel.js

Adds a textfield to the CSWMetadataPanel to show license information (or any other constraints) as a simple comma separated list. The textfield won't be added if there are no constraints.
To test:
* Select "Available Services" -> "<any service>"
* Click the metadata button for a service in the search results that appear.

VGLOPS-3: Constraints textfield to show license information on metadata panel

---

src/main/java/org/auscope/portal/core/services/responses/csw/CSWRecordTransformer.java

Changed the CWS record transformer's "other" constraints XPath to cater for the few records that have a slightly different XML structure.
This can be tested by displaying the metadata panel with the "Complete Bouguer Gravity Anomaly Grid of Onshore Australia 2016" or "Bouguer Gravity Anomaly Grid of Onshore Australia 2016" CWS records.

VGLOPS 3 - License info (XPath modification)

---

src/main/webapp/portal-core/js/portal/layer/downloader/wfs/KLWFSDownloader.js
src/main/webapp/portal-core/js/portal/layer/downloader/wfs/WFSDownloader.js

1. Fixes problem that downloads do not work unless layer has been added to map
Tested 'getParameters()' to make sure that downloads occur only when there are parameters to send to the service
2. Fixes problem that option to display "current visible map bounds" is usable, yet map has not been loaded
Problem is caused by 'currentlyVisibleBBox' and 'originallyVisibleBBox' being undefined, not 'null' when map has not been added, so the '=== null' tests etc. do not work, replaced with a more robust test

AUS-2774 Fixed problem with empty download when layer has not been added

---

src/main/webapp/portal-core/js/portal/layer/querier/coverage/WCSQuerier.js
src/main/webapp/portal-core/js/portal/util/Ajax.js

Two main fixes:
* Errors thrown from Ajax callback no longer cause the Ajax callback to be refired
* Fixed JS error when loading WCS querier popup

VGLOPS-20 Fixed endless loading on WCS Querier

---

src/main/java/org/auscope/portal/core/services/csw/CSWServiceItem.java

I have added a new constructor which allow the setting of 'cqlQuery', in addition to the normal set of parameters. 'cqlQuery' is already implemented within the 'CSWServiceItem' class.
This will be used to limit the number of CSW records downloaded from a service to save bandwidth and CPU time, only downloading the records that we need.

AUS-2788 New constructor allows use of CQL query

---

src/main/webapp/portal-core/js/portal/widgets/panel/CSWMetadataPanel.js

European Space Agency InSAR catalogue has moved to a new URL.
This just updates the code in line with that change.

AUS-2790 Rename URL because catalogue has moved

---

pom.xml

We currently depend on the snapshot grouping of repositories in the AuScope nexus instance. This ensures that they are referenced correctly

Added AuScope snapshot repo

---

src/main/webapp/portal-core/js/portal/widgets/panel/recordpanel/RecordPanel.js

If the record panel is initially hidden (eg another tab) the empty text will be updated to ALWAYS show irrespective of whether it should/should not. This is a quirk of the way we check for visibility. Rather than rejigging the whole checking mechanism with our own custom visbility flags, I've opted to recheck empty text when this component is made visible.
See https://jira.csiro.au/browse/AUS-2811

AUS-2811 Fixed empty text showing if cmp is initially hidden

---

src/main/webapp/portal-core/js/portal/layer/Layer.js
src/main/webapp/portal-core/js/portal/widgets/panel/FilterPanel.js

Made the widely used function getAllOnlineResources in Layer.js return only OR's that are NOT failing according to Nagios. 
Updated the warning message when adding layers to properly reflect this.

AUS-2827 "Hiding" online resources from known bad hosts

---

pom.xml

Update version of saxon library to enable Uni of Melbourne MSCL borehole plots to work again
I have re-tested AuScope functionality that uses saxon to check that there are no side-effects: e.g. IRIS, QLD Mineral Tenements, borehole counting, Yilgarn specimen chemical data, pressure DB observations etc.

AUS 2846: Update version of saxon library to enable Uni of Melbourne MSCL borehole plots to work again

---

src/main/java/org/auscope/portal/core/services/methodmakers/filter/csw/CSWGetDataRecordsFilter.java

Used by eCat to query on internal IDs, necessary for Onshore Seismic Surveys

Add AlternateIdentifier to filter

---

src/test/java/org/auscope/portal/core/services/TestCSWCacheService.java

On some machines, the thread sleep is not long enough and the cache process isn't finished before we test it.

Fix breaking test, thread sleep not long enough

---

pom.xml

Update to newer versions of 3rd party libraries as old versions no longer available through any of the maven repositories we use.
Also changed to new CSIRO repository as old one does no longer work with current versions of Java 8 or 9 (due to weak certificate which Java refuses to work with)

Update to 3rd party libraries and switch to new CSIRO maven repo

---

.gitignore
src/main/java/org/auscope/portal/core/services/VocabularyCacheService.java
src/main/java/org/auscope/portal/core/services/VocabularyService.java
src/main/java/org/auscope/portal/core/services/methodmakers/VocabularyMethodMaker.java
src/main/java/org/auscope/portal/core/services/vocabs/VocabularyServiceItem.java
src/main/resources/org/auscope/portal/core/test/responses/vocabulary/commodityConcepts_MoreData.xml
src/main/resources/org/auscope/portal/core/test/responses/vocabulary/commodityConcepts_NoMoreData.xml
src/main/resources/org/auscope/portal/core/test/responses/vocabulary/mineStatusConcepts_NoMoreData.xml
src/main/resources/org/auscope/portal/core/test/responses/vocabulary/occurrenceType_ResourceRDF.xml
src/main/resources/org/auscope/portal/core/test/responses/vocabulary/timescaleConcepts_MoreData.xml
src/main/resources/org/auscope/portal/core/test/responses/vocabulary/timescaleConcepts_NoMoreData.xml
src/test/java/org/auscope/portal/core/services/TestVocabularyCacheService.java
src/test/java/org/auscope/portal/core/services/TestVocabularyService.java
src/test/java/org/auscope/portal/core/services/methodmakers/TestVocabularyMethodMaker.java

We had a couple of vocabs that had latency problems, commodities (6 seconds) and timescales (14 seconds). To address this, we cache the vocabulary endpoints the same way we cache CSW endpoints, by wiring VocabularyServiceItems in a bean configuration, and making calls to each in independent threads.
The code here works the same as the CSW caching. There are a few new classes that are variations of the old SISSVoc classes - VocabularyService and VocabularyMethodMaker differ to their respective SISSVoc3Service and SISSVoc3Methodmaker. The latter are retained for backwards compatibility, the two new ones are added to drop the 'repository' concept as it no longer really makes sense in light of using multiple vocab APIs (AusGIN uses three separate APIs). Furthermore the timescales repository …

Vocabulary caching

---

src/main/java/org/auscope/portal/core/services/VocabularyCacheService.java
src/main/java/org/auscope/portal/core/services/VocabularyFilterService.java
src/main/java/org/auscope/portal/core/services/VocabularyService.java
src/main/java/org/auscope/portal/core/services/methodmakers/VocabularyMethodMaker.java
src/test/java/org/auscope/portal/core/services/TestVocabularyCacheService.java
src/test/java/org/auscope/portal/core/services/TestVocabularyFilterService.java

This is to improve performance of SLD queries where vocabulary terms have narrower and narrowerTransitive relationships.
The Jena model is cached fully instead of filtering for prefLabel relationships and storing as key-value pairs. 
The VocabularyFilterService is a new service class that allows querying and transform for the cached models.

Cache Jena model for vocabularies instead of key-value pairs of preflabel and URI

---

src/main/java/org/auscope/portal/core/uifilter/mandatory/UICheckbox.java
src/main/java/org/auscope/portal/core/uifilter/mandatory/UIDropDownSelectList.java
src/main/java/org/auscope/portal/core/uifilter/mandatory/UIHiddenParam.java
src/main/java/org/auscope/portal/core/uifilter/mandatory/UIHiddenResourceAttribute.java
src/main/java/org/auscope/portal/core/uifilter/mandatory/UITextBox.java
src/main/java/org/auscope/portal/core/uifilter/optional/xpath/UIDate.java
src/main/java/org/auscope/portal/core/uifilter/optional/xpath/UIDropDownRemote.java
src/main/java/org/auscope/portal/core/uifilter/optional/xpath/UIDropDownSelectList.java
src/main/java/org/auscope/portal/core/uifilter/optional/xpath/UIPolygonBBox.java
src/main/java/org/auscope/portal/core/uifilter/optional/xpath/UITextBox.java

Better for encapsulation and serialisation (don't get the doubling up of 'TYPE' and 'type')

Change public variables to private constants

---

src/main/webapp/portal-core/js/portal/map/openlayers/primitives/WMSOverlay.js

Adds parameters if there is an associated WCS service. These are ignored by other WMS vendors, but used by THREDDS to style their layers.

Add transparency for ASTER Maps

---

src/main/java/org/auscope/portal/core/services/cloud/CloudStorageServiceJClouds.java
src/test/java/org/auscope/portal/core/services/cloud/TestCloudStorageService.java

VGL was hanging for a minute or 2 whilst attempting to clean up job files it couldn't find, so I've added a simple check in the underlying CloudStorageServiceJClouds.deleteJobFiles method that ensures the requested object is there before attempting to delete it.

Check job object exists before attepting to delete it

---

src/main/java/org/auscope/portal/core/server/controllers/WMSController.java
src/main/java/org/auscope/portal/core/services/responses/wms/GetCapabilitiesRecord.java
src/main/java/org/auscope/portal/core/services/responses/wms/GetCapabilitiesRecord_1_1_1.java
src/main/java/org/auscope/portal/core/services/responses/wms/GetCapabilitiesRecord_1_3_0.java

We use the applicationProfile property to report on the service vendor

For custom WMS layers, embed the vendor in the response

---

src/main/java/org/auscope/portal/core/server/controllers/BaseCSWController.java
src/main/java/org/auscope/portal/core/view/ViewCSWRecordFactory.java
src/test/java/org/auscope/portal/core/server/controllers/TestBaseCSWController.java

Fixes issue where some known layers reported failing hosts for services that weren't part of the known layer

Check whether failing host is in set of endpoint for layer

---

src/main/java/org/auscope/portal/core/server/controllers/BaseCSWController.java
src/main/java/org/auscope/portal/core/services/Nagios4CachedService.java
src/main/java/org/auscope/portal/core/services/Nagios4Service.java
src/main/java/org/auscope/portal/core/services/methodmakers/Nagios4MethodMaker.java
src/main/java/org/auscope/portal/core/view/knownlayer/KnownLayer.java
src/test/java/org/auscope/portal/core/server/controllers/TestBaseCSWController.java
src/test/java/org/auscope/portal/core/services/TestNagios4Service.java

added serviceGroup filter parameter to nagios configuration to enable more control over the nagios checks which are required to pass for a layer to be considered functional.  This enables detection of partial outages to allow functional layers to continue to be used even when others on the same server are not working.
Also, a minor jena package update for security.

added serviceGroup filter parameter to nagios configuration

---

pom.xml
src/main/java/org/auscope/portal/core/services/cloud/CloudComputeServiceAws.java
src/main/java/org/auscope/portal/core/services/cloud/CloudComputeServiceNectar.java
src/main/java/org/auscope/portal/core/services/cloud/CloudStorageService.java
src/main/java/org/auscope/portal/core/services/cloud/CloudStorageServiceJClouds.java
src/main/java/org/auscope/portal/core/services/csw/CSWServiceItem.java
src/main/java/org/auscope/portal/core/services/responses/csw/CSWGetRecordResponse.java
src/test/java/org/auscope/portal/core/services/cloud/MockCloudStorageService.java
src/test/java/org/auscope/portal/core/services/cloud/TestCloudComputeService.java
src/test/java/org/auscope/portal/core/services/cloud/TestCloudStorageService.java

* Added support for AWS session tokens.
* Now uses a shaded version of JClouds (was needed due to GeoDEVL project's use of Spring Boot that requires a later version of Google GSON that is incompatible with the one needed by JClouds).
* Support for both MD_Metadata and MI_Metadata.
* Added missing getters/setters and a no argument constructor to CSWServiceItem to allow data binding.

AWS session tokens and shaded JClouds

---

pom.xml
src/main/java/org/auscope/portal/core/services/cloud/CloudComputeServiceNectar.java
src/main/java/org/auscope/portal/core/services/cloud/CloudStorageServiceJClouds.java
src/test/java/org/auscope/portal/core/services/cloud/TestCloudStorageService.java

* Upgraded shaded JClouds to 2.1.2 for Keystone v3 compatibility.
* Updated cloud compute service and storage to use Keystone v3.

JClouds Keystone v3 upgrade

---

src/main/java/org/auscope/portal/core/services/cloud/CloudStorageServiceJClouds.java

Use base key stored with job info when listing job files instead of constructing the base key anew each time. Currently fails if the hostname changes (e.g. if running in a docker container that is recreated or if replicated across multiple hosts behind a proxy).
Fixes the bug in https://jira.csiro.au/browse/AUS-3274, but not the potential for s3 bucket proliferation or leaking private hostnames into user AWS accounts.

Use stored base key when listing job files

---

src/main/java/org/auscope/portal/core/server/controllers/BaseCSWController.java
src/main/java/org/auscope/portal/core/server/controllers/WCSController.java
src/main/java/org/auscope/portal/core/services/WCSService.java
src/main/java/org/auscope/portal/core/services/responses/wcs/CoverageOfferingBrief.java
src/main/java/org/auscope/portal/core/services/responses/wcs/GetCapabilitiesRecord_1_0_0.java
src/main/java/org/auscope/portal/core/services/responses/wcs/SimpleTimePosition.java
src/main/resources/org/auscope/portal/core/test/responses/wcs/GetCapabilitiesResponse1.xml
src/test/java/org/auscope/portal/core/services/responses/wcs/TestGetCapabilities.java

* Added request to return minimal implementation of WCS GetCapabilities v1.0.0, currently returning capabilities map and CoverageOfferingBrief objects.
* Fixed missing RequestParameters in DescribeCoverage endpoint.
* Added a second date/time pattern to SimpleTimePosition so that date/times can specify milliseconds.

Add WCS GetCapabilities v1.0.0 request/response

---

src/main/java/org/auscope/portal/core/configuration/ServiceConfiguration.java
src/main/java/org/auscope/portal/core/server/controllers/CSWCacheController.java
src/main/java/org/auscope/portal/core/server/controllers/CSWSearchController.java
src/main/java/org/auscope/portal/core/services/LocalCSWFilterService.java
src/main/java/org/auscope/portal/core/services/csw/GriddedCSWRecord.java
src/main/java/org/auscope/portal/core/services/csw/GriddedCSWRecordTransformer.java
src/main/java/org/auscope/portal/core/services/csw/GriddedCSWRecordTransformerFactory.java
src/main/java/org/auscope/portal/core/services/csw/GriddedDataPositionalAccuracy.java
src/main/java/org/auscope/portal/core/services/csw/SearchFacet.java
src/main/java/org/auscope/portal/core/services/csw/ViewGriddedCSWRecordFactory.java
src/main/java/org/auscope/portal/core/services/responses/search/FacetedMultiSearchResponse.java
src/main/java/org/auscope/portal/core/services/responses/search/FacetedSearchResponse.java
src/test/java/org/auscope/portal/core/server/controllers/TestCSWCacheController.java
src/test/java/org/auscope/portal/core/server/controllers/TestCSWSearchController.java
src/test/java/org/auscope/portal/core/services/TestLocalCSWFilterService.java

Moved all of VGL's CSW search classes into portal-core so they can be used by other projects.
Only actual change to existing portal-core components was adding a Component annotation to ServiceConfiguration so it can be autowired.

Merge VGL CSW search functionality into portal-core

---

src/main/java/org/auscope/portal/core/configuration/ServiceConfiguration.java

Was using a Component annotation to pull the bean in via Spring Boot's component scan, will manually create beans that use ServiceConfiguation (such as DownloadController) instead.

ServiceConfiguration's Component annotation was breaking other projects.

---

src/main/java/org/auscope/portal/core/util/SLDLoader.java

Allows the loading of a plain SLD, and injecting ogc:Filters into rules at the correct XPath

Add loading of SLD file with filter

---

src/main/java/org/auscope/portal/core/services/cloud/CloudComputeService.java

NCI has retired Raijin and replaced it with Gadi. Most of the changes will be in VGL, but one enum needs to be changed in portal-core.

Changed Raijin to Gadi

---

pom.xml
src/main/java/org/auscope/portal/core/cloud/CloudJob.java

Added a few basic annotations so that classes that extend CloudJob can persist its fields.
This was an issue for ANVGL-Portal which uses annotation based persistence and had to shadow CloudJob's variables so that the subclass (VEGLJob) was able to persist them.

Annotate CloudJob to assist with subclass persistence

---

src/main/java/org/auscope/portal/core/cloud/MachineImage.java

Adds annotations property to the MachineImage class to support the current version of the SSSC. Requires the corresponding support in the portal API (pull request pending). If job submission is available in the frontend (e.g. ngvl) then the corersponding support is required there too (pull request pending).

Added annotations to MachineImage

---

src/main/resources/org/auscope/portal/core/xslt/WfsToHtml.xsl

Changed so it picks it up from uomLabels. To test locally:
1. Add Boreholes -> MSCL data to map.
- Click on a feature and bring up a pop up.
- Click on the identifier link on top. It should bring up another pop up.
- In the second pop up, check that "elevation", "cored interval (upper corner)", "cored interval (lower corner)" doesn't have "m" or any metrics in the end. This may seem wrong, but it is correct according to the data (it's not specified in the XML). 
i.e. http://meiproc.earthsci.unimelb.edu.au/geoserver/wfs?service=WFS&version=1.1.0&request=GetFeature&typeName=gsml:Borehole&featureid=100 uomLabels aren't specified in the relevant nodes. 
2. Add Boreholes -> National virtual core library to map.
- Click on a feature in WA and bring up a pop up.
- Click on the identifier link on …

AUS-3464: Borehole HTML assumes elevation and cored interval in meters

---

pom.xml
src/main/java/org/auscope/portal/core/services/cloud/CloudComputeServiceNectar.java
src/main/java/org/auscope/portal/core/services/cloud/CloudStorageServiceJClouds.java
src/test/java/org/auscope/portal/core/services/cloud/TestCloudComputeService.java
src/test/java/org/auscope/portal/core/services/cloud/TestCloudStorageService.java

Very simple changes, JClouds upgraded to latest version and all corresponding imports updated.

Upgrade JClouds, no longer need shaded version

---

.gitignore
src/main/java/org/auscope/portal/core/server/controllers/WMSController.java

Allow our getWMSMapViaProxy.do endpoint to accept WMS version < 1.3.0 requests using the SRS parameter.
Test by displaying the Geological Provinces layer, which is hosted on a version 1.1.1 WMS. Note that this will currently only work on Chrome due to an unrelated rendering bug in Firefox/Safari.

WMS proxy accepts version < 1.3 SRS parameter

---

src/main/java/org/auscope/portal/core/server/controllers/WMSController.java

getWMSMapViaProxy uses non standard parameters layer and sldBody.  Updated it to accept the standard getmap parameters sld_body and layers.  Backward compatibility is maintained. Note: springboot parameters are case-sensitive but geoserver is not.

updated getWMSMapViaProxy to accept standard getmap parameters

---

src/main/java/org/auscope/portal/core/server/controllers/DownloadController.java
src/main/java/org/auscope/portal/core/server/http/download/DownloadTracker.java
src/main/java/org/auscope/portal/core/util/FileIOUtil.java
src/test/java/org/auscope/portal/core/server/controllers/TestBasePortalController.java
src/test/java/org/auscope/portal/core/server/controllers/TestDownloadController.java

Exclude creating CSV files for services that do not intersect the specified download bounds by only writing files that contain a minimum of 2 lines (header plus at least one data row).

AUS-3705 Empty CSV Downloads

---

src/main/java/org/auscope/portal/core/uifilter/GenericFilterAdapter.java

Set XPath filters in adapter to an empty string if none have been supplied to avoid errors later.

AUS-3886 Map Legends

---

src/main/java/org/auscope/portal/core/services/CSWCacheService.java

Prevent cached CSW results from being overwritten if the registry returns zero results during caching.

AUS-4005 Zero CSW results oberwriting cache

---

src/main/java/org/auscope/portal/core/services/responses/csw/CSWSuggestion.java

Construct Completion field when CSWSuggestion is created so weights reflect the word occurrence count and higher values will take priority in suggestion queries.

Improve Suggestion Relevance
